package com.qf.express.message.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2018-11-05T15:08:14.370+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebService(targetNamespace = "http://service.message.express.qf.com/", name = "MsgService")
public interface MsgService {
	@WebMethod
	public void sendTs(String channel,String message);
	@WebMethod
	public void sendQjCms(String phone, String name, String store) throws Exception;
    @WebMethod
    @RequestWrapper(localName = "sendCheckSms", targetNamespace = "http://service.message.express.qf.com/", className = "com.qf.express.message.client.SendCheckSms")
    @ResponseWrapper(localName = "sendCheckSmsResponse", targetNamespace = "http://service.message.express.qf.com/", className = "com.qf.express.message.client.SendCheckSmsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sendCheckSms(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception;
}
